"""
PGC Adapter: ClaudeCodeAdapter — translates PGCDocument into CLAUDE.md.

Generates a Claude Code-compatible CLAUDE.md file that encodes
governance rules as system-level constraints.
"""

from typing import Dict, List

from pgc_adapter.base import BaseAdapter
from pgc_core.model import (
    PGCDocument,
    Persona,
    GovernanceBinding,
    AuthorityLevel,
    ViolationPolicy,
)


class ClaudeCodeAdapter(BaseAdapter):
    """Translates PGCDocument into Claude Code's CLAUDE.md format."""

    def render(self, document: PGCDocument) -> Dict[str, str]:
        """Render PGCDocument to CLAUDE.md.

        Args:
            document: A validated PGC governance document.

        Returns:
            Dict[str, str]: {"CLAUDE.md": <rendered content>}
        """
        sections: List[str] = [
            self._render_header(),
            self._render_roles(document.personas),
        ]

        boundaries = self._render_boundaries(document.personas)
        if boundaries:
            sections.append(boundaries)

        sections.append(self._render_governance(document))

        output_targets = self._render_output_targets(document.personas)
        if output_targets:
            sections.append(output_targets)

        capabilities = self._render_capabilities(document.capabilities)
        if capabilities:
            sections.append(capabilities)

        return {"CLAUDE.md": "\n\n".join(sections)}

    def get_target_runtime(self) -> str:
        """Return the runtime identifier."""
        return "claude-code"

    def get_target_runtime_version(self) -> str:
        """Return the supported Claude Code runtime version."""
        return "claude-code@1.0"

    def get_supported_extensions(self) -> List[str]:
        """Return supported file extensions."""
        return [".md"]

    # --- Private rendering methods ---

    def _render_header(self) -> str:
        return (
            "# CLAUDE.md\n\n"
            "> Auto-generated by PGC (Persona-Governance-Capability) Adapter for Claude Code.\n"
            "> DO NOT edit manually — regenerate from your .pgc.yaml source.\n\n"
            "---"
        )

    def _render_roles(self, personas: List[Persona]) -> str:
        lines = ["## Role & Responsibilities\n"]
        for p in personas:
            lines.append(f"### {p.name} (`{p.id}`)\n")
            for r in p.responsibilities:
                lines.append(f"- {r}")
            lines.append("")
        return "\n".join(lines).rstrip()

    def _render_boundaries(self, personas: List[Persona]) -> str:
        all_boundaries: List[str] = []
        for p in personas:
            for b in p.negative_boundaries:
                all_boundaries.append(f"- **[{p.name}]** NEVER: {b}")

        if not all_boundaries:
            return ""

        header = (
            "## Absolute Boundaries\n\n"
            "> **NEVER** violate these boundaries under any circumstances.\n"
        )
        return header + "\n".join(all_boundaries)

    def _render_governance(self, document: PGCDocument) -> str:
        gate_map = {g.id: g for g in document.governance_gates}
        cap_map = {c.id: c for c in document.capabilities}
        persona_map = {p.id: p for p in document.personas}

        # Determine violation policy for each binding
        authority = document.governance_authority
        has_strict = False

        rows: List[str] = []
        for binding in document.governance_bindings:
            gate = gate_map.get(binding.gate_id)
            if not gate:
                continue

            # Resolve violation policy
            if authority and binding.gate_id in authority.gate_overrides:
                policy = authority.gate_overrides[binding.gate_id].value
            elif authority:
                policy = authority.default_violation_policy.value
            else:
                policy = ViolationPolicy.BLOCK.value

            authority_label = binding.authority_level.value
            if binding.authority_level == AuthorityLevel.STRICT:
                has_strict = True

            rows.append(
                f"| {gate.description} | `{gate.id}` | {authority_label} | {policy} |"
            )

        header = "## Governance Rules\n"
        table_header = (
            "\n| Rule | Gate | Authority | On Violation |\n"
            "|------|------|-----------|-------------|"
        )
        table_body = "\n".join(rows)

        footer = ""
        if has_strict:
            footer = (
                "\n\n> When a STRICT rule is violated: "
                "**STOP and ask for human review.**"
            )

        return header + table_header + "\n" + table_body + footer

    def _render_output_targets(self, personas: List[Persona]) -> str:
        if not personas:
            return ""

        lines = ["## Output Targets\n"]
        lines.append("| Persona | Target |")
        lines.append("|---------|--------|")
        for p in personas:
            lines.append(f"| {p.name} | {p.output_target} |")
        return "\n".join(lines)

    def _render_capabilities(self, capabilities) -> str:
        if not capabilities:
            return ""

        lines = ["## Capabilities\n"]
        lines.append("| Capability | Owner | Description |")
        lines.append("|-----------|-------|-------------|")
        for c in capabilities:
            lines.append(f"| `{c.id}` | {c.owner_persona} | {c.description} |")
        return "\n".join(lines)
